<!-- login.phtml -->
<form method="post" action="/login" class="uk-form-stacked uk-margin-large">
    <fieldset class="uk-fieldset">

        <legend class="uk-legend"><?= $title ?></legend>

        <?php if (isset($error)) : ?>
            <div class="uk-alert-danger" uk-alert>
                <a class="uk-alert-close" uk-close></a>
                <p><?= $error; ?></p>
            </div>
        <?php endif; ?>

        <div class="uk-margin">
            <label class="uk-form-label" for="email">Email</label>
            <div class="uk-form-controls">
                <input class="uk-input" id="email" type="email" name="email" required>
            </div>
        </div>

        <div class="uk-margin">
            <label class="uk-form-label" for="password">Password</label>
            <div class="uk-form-controls">
                <input class="uk-input" id="password" type="password" name="password" required>
            </div>
        </div>

        <div class="uk-margin">
            <button class="uk-button uk-button-primary" type="submit">Login</button>
        </div>

    </fieldset>
</form>