<div class="container px-4 py-8 mx-auto">
    <h2 class="mb-6"><?= $title ?></h2>
    <ul class="flex justify-center mb-8">
        <!-- Lien vers la page précédente -->
        <?php if ($currentPage > 1) : ?>
            <li class="mx-1">
                <a href="/cards/<?= $currentPage - 1 ?>" class="px-3 py-2 text-gray-800 bg-gray-200 rounded hover:bg-gray-300">Précédent</a>
            </li>
        <?php endif; ?>

        <!-- Afficher les numéros de page progressivement -->
        <?php
        // Calculer le début et la fin de la boucle pour afficher les numéros de page
        $start = max(1, $currentPage - 2);
        $end = min($totalPages, $currentPage + 2);

        // Afficher les liens de page
        for ($i = $start; $i <= $end; $i++) : ?>
            <li class="mx-1">
                <a href="/cards/<?= $i ?>" class="px-3 py-2 <?= $i == $currentPage ? 'bg-blue-600 text-white' : 'bg-gray-200 text-gray-800 hover:bg-gray-300' ?> rounded">
                    <?= $i ?>
                </a>
            </li>
        <?php endfor; ?>

        <!-- Lien vers la page suivante -->
        <?php if ($currentPage < $totalPages) : ?>
            <li class="mx-1">
                <a href="/cards/<?= $currentPage + 1 ?>" class="px-3 py-2 text-gray-800 bg-gray-200 rounded hover:bg-gray-300">Suivant</a>
            </li>
        <?php endif; ?>
    </ul>
    <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
        <?php foreach ($cards as $card) : ?>
            <div class="p-4 text-center bg-white rounded shadow">
                <img src="<?= $card['card_images'][0]['image_url'] ?>" alt="<?= $card['name'] ?>" class="object-cover w-full h-auto">
                <h2 class="mt-2 text-lg font-semibold">
                    <a href="/card/<?= $card['id'] ?>">
                        <?= $card['name'] ?>
                    </a>
                </h2>
                <?php if ($card['type'] == 'Spell Card' || $card['type'] == 'Trap Card') : ?>
                    <p class="mt-2">
                        <?= $card['race'] . ' ' . $card['type'] ?>
                    </p>

                <?php else : ?>
                    <p class="mt-2">
                        <?= $card['type'] ?>
                    </p>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>

    <ul class="flex justify-center mt-8">
        <!-- Lien vers la page précédente -->
        <?php if ($currentPage > 1) : ?>
            <li class="mx-1">
                <a href="/cards/<?= $currentPage - 1 ?>" class="px-3 py-2 text-gray-800 bg-gray-200 rounded hover:bg-gray-300">Précédent</a>
            </li>
        <?php endif; ?>

        <!-- Afficher les numéros de page progressivement -->
        <?php
        // Calculer le début et la fin de la boucle pour afficher les numéros de page
        $start = max(1, $currentPage - 2);
        $end = min($totalPages, $currentPage + 2);

        // Afficher les liens de page
        for ($i = $start; $i <= $end; $i++) : ?>
            <li class="mx-1">
                <a href="/cards/<?= $i ?>" class="px-3 py-2 <?= $i == $currentPage ? 'bg-blue-600 text-white' : 'bg-gray-200 text-gray-800 hover:bg-gray-300' ?> rounded">
                    <?= $i ?>
                </a>
            </li>
        <?php endfor; ?>

        <!-- Lien vers la page suivante -->
        <?php if ($currentPage < $totalPages) : ?>
            <li class="mx-1">
                <a href="/cards/<?= $currentPage + 1 ?>" class="px-3 py-2 text-gray-800 bg-gray-200 rounded hover:bg-gray-300">Suivant</a>
            </li>
        <?php endif; ?>
    </ul>
</div>