<div class="card-area">
    <div class="column1">
        <div class="card-image">
            <figure>
                <img title="<?= $card['name'] ?>" loading="lazy" src="<?= $card['card_images'][0]['image_url'] ?>" alt="<?= $card['name'] ?>" />
            </figure>
        </div>
    </div>
    <div class="column2">
        <div class="card-name">
            <h1>
                <?= $title ?>
            </h1>
        </div>
        <ul class="card-data-info">
            <?php if ($card['type'] == "Spell Card" || $card['type'] == "Trap Card") : ?>
                <li>
                    <span class="card-data-header text-info">
                        Type
                    </span>
                    <span class="card-data-cost card-data-subheader">
                        <i class="fa-solid fa-book"></i>
                        <a href="#" target="_blank">
                            <?= $card['race'] . ' ' . $card['type'] ?>
                        </a>
                    </span>
                </li>
            <?php else : ?>
                <li>
                    <span class="card-data-header text-info">
                        Type
                    </span>
                    <span class="card-data-cost card-data-subheader">
                        <i class="fa-solid fa-book"></i>
                        <a href="#" target="_blank">
                            <?= $card['type'] ?>
                        </a>
                    </span>
                </li>
                <li>
                    <span class="card-data-header text-info">
                        Typing
                    </span>
                    <span class="card-data-cost card-data-subheader">
                        <img class="card-typing-icon" src="https://images.ygoprodeck.com/images/cards/icons/race/<?= $card['race'] ?>.png" alt="<?= $card['race'] ?>" title="<?= $card['race'] ?>" loading="lazy">
                        <a href="#" target="_blank">
                            <?= $card['race'] ?>
                        </a>
                    </span>
                </li>
            <?php endif;
            if (isset($card['attribute'])) : ?>
                <li>
                    <span class="card-data-header text-info">
                        Attribute
                    </span>
                    <span class="card-data-cost card-data-subheader">
                        <img class="card-typing-icon" src="https://images.ygoprodeck.com/images/cards/<?= $card['attribute'] ?>.jpg" alt="$card['attribute']" title="$card['attribute']" loading="lazy">
                        <a href="#" target="_blank">
                            <?= $card['attribute'] ?>
                        </a>
                    </span>
                </li>
            <?php endif;
            if (isset($card['level'])) : ?>
                <li>
                    <span class="card-data-header text-info">
                        Level/Rank
                    </span>
                    <span class="card-data-cost card-data-subheader">
                        <img class="card-typing-icon" src="https://ygoprodeck.com/wp-content/uploads/2017/01/level.png" alt="level : <?= $card['level'] ?>" title="level : <?= $card['level'] ?>" loading="lazy" />
                        <a href="#" target="_blank">
                            <?= $card['level'] ?>
                        </a>
                    </span>
                </li>
            <?php endif;
            if (isset($card['scale'])) : ?>
                <li>
                    <span class="card-data-header text-info">
                        Pendulum Scale
                    </span>
                    <span class="card-data-cost card-data-subheader">
                        <img class="card-typing-icon" src="https://www.db.yugioh-card.com/yugiohdb/external/image/parts/icon_pendulum.png" alt="scale : <?= $card['scale'] ?>" title="scale : <?= $card['scale'] ?>" loading="lazy" />
                        <a href="#" target="_blank">
                            <?= $card['scale'] ?>
                        </a>
                    </span>
                </li>
            <?php endif;
            if (isset($card['linkval'])) : ?>
                <li>
                    <span class="card-data-header text-info">
                        Link Value
                    </span>
                    <span class="card-data-cost card-data-subheader">
                        <img class="card-typing-icon" src="https://ygoprodeck.com/wp-content/uploads/2017/01/level.png" alt="link : <?= $card['linkval'] ?>" title="link : <?= $card['linkval'] ?>" loading="lazy" />
                        <a href="#" target="_blank">
                            <?= $card['linkval'] ?>
                        </a>
                    </span>
                </li>
            <?php endif;
            if (isset($card['atk'])) : ?>
                <li>
                    <span class="card-data-header text-info">
                        ATK
                    </span>
                    <span class="card-data-cost card-data-subheader">
                        <img class="card-typing-icon" src="/img/swords.png" title=" attack : <?= $card['atk'] ?>" loading="lazy" />
                        <a href="#" target="_blank">
                            <?= $card['atk'] ?>
                        </a>
                    </span>
                </li>
            <?php endif;
            if (isset($card['def'])) : ?>
                <li>
                    <span class="card-data-header text-info">
                        DEF
                    </span>
                    <span class="card-data-cost card-data-subheader">
                        <i class="fa-solid fa-shield" title="defense : <?= $card['def'] ?>"></i>
                        <a href="#" target="_blank">
                            <?= $card['def'] ?>
                        </a>
                    </span>
                </li>
            <?php endif;
            if (isset($card['archetype'])) : ?>
                <li>
                    <span class="card-data-header text-info">
                        Archetype
                    </span>
                    <span class="card-data-cost card-data-subheader">
                        <img class="card-typing-icon" title="archetype : <?= $card['archetype'] ?>" src="/img/roundflask.png" alt="<?= $card['archetype'] ?>" />
                        <a href="#" target="_blank">
                            <?= $card['archetype'] ?>
                        </a>
                    </span>
                </li>
            <?php else : ?>
                <li>
                    <span class="card-data-header text-info">
                        Archetype
                    </span>
                    <span class="card-data-cost card-data-subheader">
                        <img class="card-typing-icon" src="/img/roundflask.png" alt="This Card has no Archetype" title="This Card has no Archetype" />
                        <a>
                            This Card has no Archetype
                        </a>
                    </span>
                </li>
            <?php endif; ?>
        </ul>
        <hr class="m-3">
        <?php
        if (isset($card['pend_desc'])) : ?>
            <h4>
                Pendulum Effect:
            </h4>
            <div class="card-text ">
                <?= $card['pend_desc'] ?>
            </div>
            <hr class="m-3">
            <h4>
                Monster Text / Monster Effect
            </h4>
            <div class="card-text ">
                <?= $card['monster_desc'] ?>
            </div>
        <?php else : ?>
            <h4>
                Card description/effect
            </h4>
            <div class="card-text">
                <?= $card['desc'] ?>
            </div>
        <?php endif; ?>
        <hr class="m-3">
    </div>
</div>